### ISSUE TITLE
Parsing performance...

### ISSUE THREAD

**Issue by leeoniya** [josdejong/csv42#3]
Hey @josdejong :wave: 

figured you might be interested: https://github.com/leeoniya/uDSV/tree/main/bench#nested-objects

hopefully i didnt leave any big stones unturned :sweat_smile: 

cheers!

**Comment by josdejong** [comment]
O wow, `uDSV` is indeed much faster than `csv42`, I did a small test to try it out myself. That's impressive. That makes me _very_ curious of course how you achieved that. It's a lot of fun to try to optimize this, isn't it 😁 ?

Reading the readme of `uDSV`, it explains "this project is to handle the 99.5% use-case", makes me immediately wonder what this non supported 0.5% is, in order to understand whether I can use the library for my use-cases or not. Maybe you can add some explanation about that? 

I had a look at the source code to understand why `uDSV` is fast, and I think I can see two main reasons:

1.  `uDSV` parses the first 10 rows (by default) to identify the _type_ of each row, and then can optimize parsing the values straight into the identified types. So the assumption here is that the CSV data is homogeneous. That is indeed often the case in practice so it's smart to utilize that knowledge. I personally would not turn that behavior on by default but let the user explicitly configure this to prevent surprises. Maybe it is an idea to change the `maxRows` option of `inferSchema` into an option `isHomogeneous` so users may better understand what the option is about.
2.  `uDSV` uses `new Function(...)` to generate an optimized parser after collecting information about the rows and their types. I think that that is your secret sauce, making the library so fast, right?

    I'm not sure if you're aware, but using `new Function(...)` or `eval(...)` can introduce security issues. As far as I can see you don't guard against that at the moment (I haven't examined the code thoroughly though, maybe you have taken care of it). Suppose that `uDSV` runs in a nodejs server that allows users to upload a CSV. An attacker can prepare a smart column name containing bad JavaScript (code injection), and get this code executed on the nodejs server. That way the attacker can execute arbitrary commands in nodejs, giving full access to the server. I've learned this hard way 😅. 

    I think in the case of `uDSV` it is possible to guard against malicious code injection by validating and limiting or escaping the column names. Still, it is something you need to be _really_ careful with, with every change you do. And even when the code is secure, in some companies and JavaScript environments there are Content Security Policies (CSP) in place that forbid usage of `new Function()` and `eval()`.

    Nowadays my rule of thumb is to simply not use `new Function`. In most cases the improved performance is not worth the security risks, the more complicated code, and the usage limitations due to security policies (and the time and frustration of consumers of my library debugging CSP issues). It is up to you of course, and the performance improvement is significant so it is interesting. It maybe helpful to add some information in the Readme about the usage of `new Function`, both to prevent surprises and to let the users know you've aware of the risks and have taken measures.

Sorry for the long reply. I really love to see some healthy competition here, and since it's open source we can learn from each other. I unfortunately can't use `uDSV` for my use-cases because of the two reasons above, but if a better library comes along I'm always open to use that instead 😄. At least you got me thinking about whether I can implement a new option `isHomogeneous`, utilizing that knowledge to further optimize parsing 🤔 .

**Comment by leeoniya** [comment]
> what this non supported 0.5% is

one could argue that the nested objects is part of it 😅. the non supported case is pretty much just handling of malformed CSVs. sadly i think this is probably more than 0.5% in real life.

> Maybe it is an idea to change the maxRows option of inferSchema into an option isHomogeneous so users may better understand what the option is about.

maybe i'll rename it to `inferLimit` or something. in my mind a CSV is homogenous by definition, so maybe non-homogenous CSVs are part of that unsupported 0.5%.

indeed, strict CSP headers would prevent the use of `parser.typed*` methods, though the core parsing pass should still work to produce tuples. (`d3-dsv` has the same notice, btw). i think adding a regexp or callback option to the schema should make it pretty easy to sanitize the keys (e.g. wrap the keys in backticks and disallow backticks via regexp in the column headers). imo the performance benefit here too juicy to not use dynamically compiled fns :)

thanks for the thoughtful / through reply! i'll add some configurable guards to the Function generator and add a note to the readme.

**Comment by leeoniya** [comment]
btw, i noticed that PapaParse + flat only flattens to one level, so is not actually comparing apples to apples. maybe im using it wrong? didnt spend too much time on it when learning the apis of 25 parsers 😮‍💨 

benchmarks are hard :(

**Comment by leeoniya** [comment]
i _think_ this closes the only two injection holes: https://github.com/leeoniya/uDSV/commit/3e9964252ab6350fe86fc465a2c3c7f1794f0373

**Comment by josdejong** [comment]
> btw, i noticed that PapaParse + flat only flattens to one level, so is not actually comparing apples to apples. maybe im using it wrong?

If that is the case I should correct the benchmarks. 

I did a test and `flatten` actually does do deep nesting:

```js
import flat from 'flat'
import Papa from 'papaparse'
import { inspect } from 'util'

const users = [{ test: 'abc', level1: { level2: { level3: { level4: 'ok' } } } }]
console.log('# users')
console.log(inspect(users, { depth: null }))
// [
//   {
//     test: 'abc',
//     level1: { level2: { level3: { level4: 'ok' } } }
//   }
// ]

const flatUsers = users.map(flat.flatten)
console.log('# flat users')
console.log(flatUsers)
// [ { test: 'abc', 'level1.level2.level3.level4': 'ok' } ]

const csv = Papa.unparse(flatUsers)
console.log('# csv')
console.log(csv)
// test,level1.level2.level3.level4
// abc,ok

const parsedFlatUsers = Papa.parse(csv, { header: true }).data
console.log('# parsed flat users')
console.log(parsedFlatUsers)
// [ { test: 'abc', 'level1.level2.level3.level4': 'ok' } ]

const parsedDeepUsers = parsedFlatUsers.map(flat.unflatten)
console.log('# parsed deep users')
console.log(inspect(parsedDeepUsers, { depth: null }))
// [
//   {
//     test: 'abc',
//     level1: { level2: { level3: { level4: 'ok' } } }
//   }
// ]
``` 

Note that to make sure the libraries actually produce the same outputs, I wrote some validation logic that runs before the benchmark: https://github.com/josdejong/csv42/blob/main/benchmark/validate.ts

Now, comparing csv42 with papa+flat still feels a bit like comparing different things to me because papaparse doesn't support nested objects by itself and needs the additional step via `flat`. My thinking was from an end user point of view, to get CSV data parsed into nested objects you need these two steps. Such a solution is also the answer for these kind of questions on StackOverflow. Most important to me is that both solutions have the same output (assuming the case that a nested object is the desired output for a user).

**Comment by josdejong** [comment]
> i _think_ this closes the only three injection holes: [leeoniya/uDSV@4e7472a](https://github.com/leeoniya/uDSV/commit/4e7472a7015c0a7ae5ae76e41f282bd4bdcf0c67)

Sounds good! I'll have a look

**Comment by josdejong** [comment]
> i _think_ this closes the only three injection holes: [leeoniya/uDSV@4e7472a](https://github.com/leeoniya/uDSV/commit/4e7472a7015c0a7ae5ae76e41f282bd4bdcf0c67)

It looks good, I expect that using `JSON.stringify` should guard against code injection. I'm not an expert though.
